// Alliance benefits comparison data

// Helper used by HOME_BENEFITS and RECIP_BENEFITS
const _b = (v, d, ok) => ({ v, d, ok: !!ok });

export const ALLIANCE_MBR = {
  ua:           { alliance:"star",     color:"#002244", tierMap:{ Silver:"sa_silver", Gold:"sa_gold", Platinum:"sa_gold", "1K":"sa_gold" }},
  aeroplan:     { alliance:"star",     color:"#F01428", tierMap:{ "25K":"sa_silver","35K":"sa_gold","50K":"sa_gold","75K":"sa_gold","100K":"sa_gold" }},
  singapore_kf: { alliance:"star",     color:"#003876", tierMap:{ "Elite Silver":"sa_silver","Elite Gold":"sa_gold" }},
  turkish_miles:{ alliance:"star",     color:"#C8102E", tierMap:{ "Classic Plus":"sa_silver","Elite":"sa_gold","Elite Plus":"sa_gold" }},
  aa:           { alliance:"oneworld", color:"#0078D2", tierMap:{ Gold:"ow_ruby",Platinum:"ow_sapphire","Platinum Pro":"ow_sapphire","Executive Platinum":"ow_emerald" }},
  ba_avios:     { alliance:"oneworld", color:"#075AAA", tierMap:{ Bronze:"ow_ruby",Silver:"ow_sapphire",Gold:"ow_emerald" }},
  qantas_ff:    { alliance:"oneworld", color:"#E0001B", tierMap:{ Silver:"ow_ruby",Gold:"ow_sapphire",Platinum:"ow_emerald" }},
  cathay_mp:    { alliance:"oneworld", color:"#006564", tierMap:{ Silver:"ow_ruby",Gold:"ow_sapphire",Diamond:"ow_emerald" }},
  dl:           { alliance:"skyteam",  color:"#003366", tierMap:{ "Silver Medallion":"st_elite","Gold Medallion":"st_elite_plus","Platinum Medallion":"st_elite_plus","Diamond Medallion":"st_elite_plus" }},
  flying_blue:  { alliance:"skyteam",  color:"#002157", tierMap:{ Silver:"st_elite",Gold:"st_elite_plus",Platinum:"st_elite_plus",Ultimate:"st_elite_plus" }},
};
export const ALLIANCE_LABELS = {
  star:"Star Alliance", oneworld:"Oneworld", skyteam:"SkyTeam",
};
export const ALLIANCE_TIER_LABELS = {
  sa_silver:"Star Alliance Silver", sa_gold:"Star Alliance Gold",
  ow_ruby:"Oneworld Ruby", ow_sapphire:"Oneworld Sapphire", ow_emerald:"Oneworld Emerald",
  st_elite:"SkyTeam Elite", st_elite_plus:"SkyTeam Elite Plus",
};
export const ALLIANCE_TIER_COLORS = {
  sa_silver:"#C0C0C0", sa_gold:"#C9A84C",
  ow_ruby:"#9B2335", ow_sapphire:"#0057A8", ow_emerald:"#006341",
  st_elite:"#00B0F0", st_elite_plus:"#004A97",
};

export const BENEFIT_ROWS = [
  { id:"free_bags",      cat:"Baggage",              label:"Free Checked Bags",          sub:"Number of free pieces in economy" },
  { id:"bag_weight",     cat:"Baggage",              label:"Weight Per Bag",             sub:"kg / lbs max per piece" },
  { id:"car_seat",       cat:"Baggage",              label:"Child Car Seat",             sub:"Is a child safety seat free & uncounted?" },
  { id:"stroller",       cat:"Baggage",              label:"Stroller / Pram",            sub:"Collapsible stroller check-in policy" },
  { id:"ski_bag",        cat:"Baggage",              label:"Ski / Snowboard Bag",        sub:"Is ski or snowboard bag free or at reduced fee?" },
  { id:"golf_bag",       cat:"Baggage",              label:"Golf Bag",                   sub:"Golf equipment policy" },
  { id:"sport_equip",    cat:"Baggage",              label:"Oversized Sports Equipment", sub:"Bicycles, surfboards, etc." },
  { id:"overweight_fee", cat:"Baggage",              label:"Overweight Fee Waiver",      sub:"Is the overweight surcharge waived?" },
  { id:"checkin",        cat:"Check-in & Boarding",  label:"Priority Check-in",          sub:"Dedicated counter or business class lane" },
  { id:"security",       cat:"Check-in & Boarding",  label:"Priority Security",          sub:"Expedited security screening lane" },
  { id:"boarding",       cat:"Check-in & Boarding",  label:"Boarding Group",             sub:"When in the boarding sequence" },
  { id:"preboard",       cat:"Check-in & Boarding",  label:"Pre-Boarding",               sub:"Board before general boarding begins" },
  { id:"seat_sel",       cat:"Seating",              label:"Free Seat Selection",        sub:"Choose seat at booking at no charge" },
  { id:"exit_row",       cat:"Seating",              label:"Exit Row / Extra Legroom",   sub:"Complimentary access to exit row seats" },
  { id:"lounge",         cat:"Lounge",               label:"Lounge Access",              sub:"Partner lounge when flying in economy" },
  { id:"lounge_guest",   cat:"Lounge",               label:"Guest Lounge Pass",          sub:"Complimentary guest access" },
  { id:"priority_bags",  cat:"In-flight & Other",    label:"Priority Baggage Delivery",  sub:"Bags arrive on belt before other passengers" },
  { id:"upgrade",        cat:"In-flight & Other",    label:"Upgrade Eligibility",        sub:"Complimentary or discounted cabin upgrade" },
  { id:"miles_bonus",    cat:"In-flight & Other",    label:"Miles / Points Bonus",       sub:"Earning bonus % on base miles" },
  { id:"fee_waiver",     cat:"In-flight & Other",    label:"Change / Cancel Fee Waiver", sub:"Standard ticket modification fees waived" },
];

export const HOME_BENEFITS = {
  aa: {
    Gold: {
      free_bags:_b("1 free","1st bag free on domestic US flights"),
      bag_weight:_b("23 kg / 50 lbs","Standard economy weight per piece"),
      car_seat:_b("Free – uncounted","Car seat does not count toward allowance",true),
      stroller:_b("Free","Gate-check or check-in, free of charge",true),
      ski_bag:_b("Counts as bag","Uses 1 free piece if within 23 kg / 50 lbs"),
      golf_bag:_b("Counts as bag","Uses 1 free piece if within weight"),
      sport_equip:_b("Fees apply","Oversized items ~$150+ per leg"),
      overweight_fee:_b("Not waived","Overweight/oversize fees still apply"),
      checkin:_b("Priority counter","Dedicated priority check-in lane",true),
      security:_b("Priority lane","Priority security at most AA hubs",true),
      boarding:_b("Group 4","Boards in Group 4, after ExPlat, Plat Pro, and Platinum"),
      preboard:_b("No","No pre-boarding; Group 4 is after general elite groups"),
      seat_sel:_b("Yes","Free preferred seat selection at booking",true),
      exit_row:_b("Yes – MCE","Free Main Cabin Extra seats incl. exit rows",true),
      lounge:_b("No","No Admiral's Club in economy ticket"),
      lounge_guest:_b("No","N/A"),
      priority_bags:_b("Yes","Priority baggage tag, arrives first",true),
      upgrade:_b("Comp. upgrades","Complimentary upgrades to F on AA metal",true),
      miles_bonus:_b("40% bonus","40% bonus on Loyalty Points earned",true),
      fee_waiver:_b("Yes","Same-day flight changes free",true),
    },
    Platinum: {
      free_bags:_b("2 free","1st & 2nd bag free",true),
      bag_weight:_b("23 kg / 50 lbs","Standard economy weight"),
      car_seat:_b("Free – uncounted","Does not count toward allowance",true),
      stroller:_b("Free","Gate or check-in, free",true),
      ski_bag:_b("Counts as bag","Uses 1 of your 2 free pieces"),
      golf_bag:_b("Counts as bag","Uses 1 of your 2 free pieces"),
      sport_equip:_b("Fees apply","~$150+ per leg"),
      overweight_fee:_b("Not waived","Oversize/overweight fees still apply"),
      checkin:_b("Priority counter","Dedicated priority counter",true),
      security:_b("Priority + Flagship","Flagship Access lanes at key hubs",true),
      boarding:_b("Group 3","Boards in Group 3, after Executive Platinum and Platinum Pro",true),
      preboard:_b("Yes","Boards before general cabin groups",true),
      seat_sel:_b("Yes","Free preferred seat at booking",true),
      exit_row:_b("Yes – MCE","Free Main Cabin Extra + exit rows",true),
      lounge:_b("No","No Admiral's Club (must buy or use credit card benefit)"),
      lounge_guest:_b("No","N/A"),
      priority_bags:_b("Yes","Priority baggage, arrives first",true),
      upgrade:_b("Comp. upgrades","Higher priority than Gold; system upgrades",true),
      miles_bonus:_b("60% bonus","60% bonus on Loyalty Points earned",true),
      fee_waiver:_b("Yes","Same-day standby free; standard fee waivers",true),
    },
    "Platinum Pro": {
      free_bags:_b("2 free","1st & 2nd bag free",true),
      bag_weight:_b("32 kg / 70 lbs","Upgraded weight allowance",true),
      car_seat:_b("Free – uncounted","Does not count toward allowance",true),
      stroller:_b("Free","Gate or check-in, free",true),
      ski_bag:_b("Free","Within 32 kg / 70 lbs weight limit",true),
      golf_bag:_b("Free","Within weight limit",true),
      sport_equip:_b("Often waived","Most standard sports equipment fees waived",true),
      overweight_fee:_b("Waived ≤70 lbs","Overweight fee waived up to 70 lbs",true),
      checkin:_b("Flagship check-in","Flagship First check-in at hubs",true),
      security:_b("Flagship Access","Dedicated Flagship Access lanes at hubs",true),
      boarding:_b("Group 2","Boards in Group 2, after Executive Platinum only",true),
      preboard:_b("Yes","Boards well ahead of general cabin groups",true),
      seat_sel:_b("Yes – full","Full seat selection incl. MCE",true),
      exit_row:_b("Yes – MCE","All MCE and exit row seats free",true),
      lounge:_b("No","No Admiral's Club with economy ticket"),
      lounge_guest:_b("No","N/A"),
      priority_bags:_b("Yes","Priority baggage, first off belt",true),
      upgrade:_b("Priority upgrades","Higher priority; instant upgrades on select fares",true),
      miles_bonus:_b("80% bonus","80% bonus on Loyalty Points",true),
      fee_waiver:_b("Full waiver","All standard change/cancel fees waived",true),
    },
    "Executive Platinum": {
      free_bags:_b("3 free","1st, 2nd & 3rd bag free",true),
      bag_weight:_b("32 kg / 70 lbs","Per bag",true),
      car_seat:_b("Free – uncounted","Does not count toward allowance",true),
      stroller:_b("Free","Gate or check-in, free",true),
      ski_bag:_b("Free","Free within 32 kg / 70 lbs",true),
      golf_bag:_b("Free","Free within weight limit",true),
      sport_equip:_b("Waived","Standard sports equipment fees waived",true),
      overweight_fee:_b("Waived ≤70 lbs","Overweight fee waived to 70 lbs",true),
      checkin:_b("Flagship First","Flagship First check-in line at all AA hubs",true),
      security:_b("Flagship Access","Dedicated lanes at all AA hubs",true),
      boarding:_b("Group 1 (first)","First among Group 1 after F/J pre-board",true),
      preboard:_b("Yes","Boards with First Class cabin",true),
      seat_sel:_b("Yes – full","Any seat incl. premium on upgrade",true),
      exit_row:_b("Yes – all MCE","All MCE & exit rows free at booking",true),
      lounge:_b("Flagship Lounge (SWU)","Access via Systemwide Upgrade cert.",true),
      lounge_guest:_b("With upgrade","Lounge access accompanies SWU upgrade"),
      priority_bags:_b("Yes – first off","First class priority baggage delivery",true),
      upgrade:_b("Systemwide upgrades","SWUs to Business/Flagship on most itineraries",true),
      miles_bonus:_b("120% bonus","120% bonus on Loyalty Points",true),
      fee_waiver:_b("Full waiver","All fees waived; last-seat award access",true),
    },
  },
  dl: {
    "Silver Medallion": {
      free_bags:_b("1 free","1st bag free"),
      bag_weight:_b("23 kg / 50 lbs","Standard economy weight"),
      car_seat:_b("Free – uncounted","Does not count toward allowance",true),
      stroller:_b("Free","Gate or check-in, free",true),
      ski_bag:_b("Counts as bag","Uses 1 free piece if within weight"),
      golf_bag:_b("Counts as bag","Uses 1 free piece"),
      sport_equip:_b("Fees apply","~$150+ per leg"),
      overweight_fee:_b("Not waived","Oversize/overweight fees apply"),
      checkin:_b("Priority counter","Priority check-in access",true),
      security:_b("Priority lane","Priority security at most hubs",true),
      boarding:_b("Zone 1","Boards after First/Delta One",true),
      preboard:_b("Yes","Pre-boards before general zones",true),
      seat_sel:_b("Yes – Comfort+","Free Comfort+ seat selection",true),
      exit_row:_b("Yes – Comfort+","Exit row Comfort+ seats included",true),
      lounge:_b("No","No Sky Club access in economy"),
      lounge_guest:_b("No","N/A"),
      priority_bags:_b("Yes","Priority baggage tag",true),
      upgrade:_b("Waitlist","Upgrade waitlist for Comfort+ / First",true),
      miles_bonus:_b("40% bonus","40% bonus on base MQMs",true),
      fee_waiver:_b("Yes","Same-day standby changes free",true),
    },
    "Gold Medallion": {
      free_bags:_b("2 free","1st & 2nd bag free",true),
      bag_weight:_b("23 kg / 50 lbs","Standard economy weight"),
      car_seat:_b("Free – uncounted","Does not count toward allowance",true),
      stroller:_b("Free","Gate or check-in, free",true),
      ski_bag:_b("Counts as bag","Uses 1 of your free pieces"),
      golf_bag:_b("Counts as bag","Uses 1 of your free pieces"),
      sport_equip:_b("Fees apply","~$150+ per leg"),
      overweight_fee:_b("Not waived","Oversize fees still apply"),
      checkin:_b("Priority counter","Priority check-in with Delta",true),
      security:_b("Priority lane","Priority security lane",true),
      boarding:_b("Zone 1 (early)","First Zone 1 boarders with Medallion priority",true),
      preboard:_b("Yes","Pre-boarding before Zone 1 opens",true),
      seat_sel:_b("Yes – Comfort+","Free Comfort+ at booking",true),
      exit_row:_b("Yes – Comfort+","Free Comfort+ exit rows",true),
      lounge:_b("No","No Sky Club without card/upgrade benefit"),
      lounge_guest:_b("No","N/A"),
      priority_bags:_b("Yes","Priority tag, arrives first",true),
      upgrade:_b("Comp. upgrades","Complimentary upgrades to First Class",true),
      miles_bonus:_b("60% bonus","60% bonus MQMs",true),
      fee_waiver:_b("Yes","Same-day confirmed changes free",true),
    },
    "Platinum Medallion": {
      free_bags:_b("2 free","1st & 2nd bag free",true),
      bag_weight:_b("32 kg / 70 lbs","Upgraded weight",true),
      car_seat:_b("Free – uncounted","Does not count toward allowance",true),
      stroller:_b("Free","Gate or check-in, free",true),
      ski_bag:_b("Free","Free within 32 kg / 70 lbs",true),
      golf_bag:_b("Free","Free within weight allowance",true),
      sport_equip:_b("Often waived","Standard sports equipment fees reduced/waived",true),
      overweight_fee:_b("Waived ≤70 lbs","Overweight waived up to 70 lbs",true),
      checkin:_b("Priority counter","Priority check-in and kiosk",true),
      security:_b("Priority lane","Delta Premium Select security lanes",true),
      boarding:_b("Zone 1 (priority)","First Zone 1 boarding call",true),
      preboard:_b("Yes","Boards with DL One at select airports"),
      seat_sel:_b("Yes – Comfort+","Free Comfort+ & preferred seats",true),
      exit_row:_b("Yes – Comfort+","Full Comfort+ incl. exit rows",true),
      lounge:_b("Choice Benefit","Sky Club access selectable as Platinum Choice Benefit"),
      lounge_guest:_b("With benefit","If Sky Club benefit is chosen"),
      priority_bags:_b("Yes","Priority baggage, first off belt",true),
      upgrade:_b("Comp. upgrades","Complimentary upgrades, higher priority",true),
      miles_bonus:_b("80% bonus","80% bonus MQMs",true),
      fee_waiver:_b("Yes","All standard fees waived",true),
    },
    "Diamond Medallion": {
      free_bags:_b("3 free","1st, 2nd & 3rd bag free",true),
      bag_weight:_b("32 kg / 70 lbs","Per bag",true),
      car_seat:_b("Free – uncounted","Does not count toward allowance",true),
      stroller:_b("Free","Gate or check-in, free",true),
      ski_bag:_b("Free","Free within 32 kg / 70 lbs",true),
      golf_bag:_b("Free","Free within weight allowance",true),
      sport_equip:_b("Waived","Sports equipment fees waived",true),
      overweight_fee:_b("Waived ≤70 lbs","Overweight waived to 70 lbs",true),
      checkin:_b("Dedicated counter","Diamond counter at major hubs",true),
      security:_b("Fastest lane","Dedicated fastest lanes at all Delta hubs",true),
      boarding:_b("Zone 1 (first)","First Diamond boarding call",true),
      preboard:_b("Yes","Boards with Delta One/First Class cabin",true),
      seat_sel:_b("Yes – full","Any seat incl. Delta One on upgrade",true),
      exit_row:_b("Yes – full","All premium seats access",true),
      lounge:_b("Sky Club included","Complimentary Sky Club + Delta One Lounge",true),
      lounge_guest:_b("3 guest passes/yr","Annual Sky Club guest passes",true),
      priority_bags:_b("Yes – first off","Diamond priority tag, first off belt",true),
      upgrade:_b("Global Upgrade Certs","Delta One GUCs included annually",true),
      miles_bonus:_b("120% bonus","120% bonus MQMs",true),
      fee_waiver:_b("Full waiver","All fees waived; confirmed same-day changes",true),
    },
  },
  ua: {
    Silver: {
      free_bags:_b("1 free","1st bag free"),
      bag_weight:_b("23 kg / 50 lbs","Standard economy weight"),
      car_seat:_b("Free – uncounted","Does not count toward allowance",true),
      stroller:_b("Free","Gate or check-in, free",true),
      ski_bag:_b("Counts as bag","Uses 1 free piece"),
      golf_bag:_b("Counts as bag","Uses 1 free piece"),
      sport_equip:_b("Fees apply","Oversized/overweight fees apply"),
      overweight_fee:_b("Not waived","Oversize fees still apply"),
      checkin:_b("Priority counter","Priority check-in counter",true),
      security:_b("Premier Access lane","At most United airports",true),
      boarding:_b("Group 2","Boards after Group 1 Premier Access"),
      preboard:_b("Yes","Before general boarding groups",true),
      seat_sel:_b("At T−48h","Economy Plus at 48-hour check-in window",true),
      exit_row:_b("At T−48h","Economy Plus exit rows at T-48h"),
      lounge:_b("No","No United Club in economy"),
      lounge_guest:_b("No","N/A"),
      priority_bags:_b("Yes","Premier priority baggage",true),
      upgrade:_b("Waitlist","Complimentary space-available upgrades waitlist"),
      miles_bonus:_b("0%","No bonus miles for Silver"),
      fee_waiver:_b("Partial","Award ticket change fee waived"),
    },
    Gold: {
      free_bags:_b("2 free","1st & 2nd bag free",true),
      bag_weight:_b("23 kg / 50 lbs","Standard economy weight"),
      car_seat:_b("Free – uncounted","Does not count toward allowance",true),
      stroller:_b("Free","Gate or check-in, free",true),
      ski_bag:_b("Counts as bag","Uses 1 of your free pieces"),
      golf_bag:_b("Counts as bag","Uses 1 of your free pieces"),
      sport_equip:_b("Fees apply","Oversized/overweight fees apply"),
      overweight_fee:_b("Not waived","Oversize fees apply"),
      checkin:_b("Premier Access","Premier Access counter",true),
      security:_b("Premier Access","Premier Access lane at all airports",true),
      boarding:_b("Group 2","Premier Access boarding group"),
      preboard:_b("Yes","Premier Access pre-boarding",true),
      seat_sel:_b("Yes","Economy Plus free at booking",true),
      exit_row:_b("Yes","Economy Plus exit rows at booking",true),
      lounge:_b("No","No United Club without card benefit"),
      lounge_guest:_b("No","N/A"),
      priority_bags:_b("Yes","Premier priority baggage handling",true),
      upgrade:_b("Comp. upgrades","Complimentary space-available upgrades on UA metal",true),
      miles_bonus:_b("25% bonus","25% bonus PQPs",true),
      fee_waiver:_b("Yes","Standard ticket change fees waived",true),
    },
    Platinum: {
      free_bags:_b("2 free","1st & 2nd bag free",true),
      bag_weight:_b("32 kg / 70 lbs","Upgraded weight",true),
      car_seat:_b("Free – uncounted","Does not count toward allowance",true),
      stroller:_b("Free","Gate or check-in, free",true),
      ski_bag:_b("Free","Within 32 kg / 70 lbs",true),
      golf_bag:_b("Free","Within weight limit",true),
      sport_equip:_b("Often waived","Standard sports fees frequently waived",true),
      overweight_fee:_b("Waived ≤70 lbs","Overweight waived to 70 lbs",true),
      checkin:_b("Premier Access","Premier Access counter",true),
      security:_b("Premier Access + Pre✓","Premier Access + TSA PreCheck lanes",true),
      boarding:_b("Group 1","First Group 1 Premier boarding",true),
      preboard:_b("Yes","Pre-board with Polaris at some airports"),
      seat_sel:_b("Yes","Economy Plus at booking",true),
      exit_row:_b("Yes","Economy Plus + UPP access when space avail"),
      lounge:_b("2 passes/yr","2 United Club one-time passes per year"),
      lounge_guest:_b("No","Passes are for member only"),
      priority_bags:_b("Yes","Priority baggage, first off belt",true),
      upgrade:_b("Comp. + 2 GPUs","Comp. upgrades + 2 Global Premier Upgrades/yr",true),
      miles_bonus:_b("50% bonus","50% bonus PQPs",true),
      fee_waiver:_b("Yes","All standard ticket fees waived",true),
    },
    "1K": {
      free_bags:_b("3 free","1st, 2nd & 3rd bag free",true),
      bag_weight:_b("32 kg / 70 lbs","Per bag",true),
      car_seat:_b("Free – uncounted","Does not count toward allowance",true),
      stroller:_b("Free","Gate or check-in, free",true),
      ski_bag:_b("Free","Within weight allowance",true),
      golf_bag:_b("Free","Within weight allowance",true),
      sport_equip:_b("Waived","Standard sports equipment fees waived",true),
      overweight_fee:_b("Waived ≤70 lbs","Overweight waived to 70 lbs",true),
      checkin:_b("Dedicated 1K counter","Dedicated 1K counter at all United airports",true),
      security:_b("Fastest lanes","Premier Access + dedicated 1K security lanes",true),
      boarding:_b("Group 1 (first)","First 1K boarding, before other Premiers",true),
      preboard:_b("Yes","Boards with Polaris cabin passengers",true),
      seat_sel:_b("Yes – full","Economy Plus + Polaris on upgrade",true),
      exit_row:_b("Yes","Full Economy Plus at booking",true),
      lounge:_b("United Club member","Complimentary United Club membership",true),
      lounge_guest:_b("2 guests/visit","2 comp. United Club guest passes per visit",true),
      priority_bags:_b("Yes – first off","Premier 1K priority, first off belt",true),
      upgrade:_b("PlusPoints + GPUs","PlusPoints for confirmed Polaris + GPUs",true),
      miles_bonus:_b("100% bonus","100% bonus PQPs (double earn)",true),
      fee_waiver:_b("Full waiver","All fees waived; last-seat partner award access",true),
    },
  },
};

// Reciprocal benefits received as a visiting elite at any partner airline
export const RECIP_BENEFITS = {
  sa_silver: {
    free_bags:_b("1 free bag","1 checked bag free; standard economy weight limit",true),
    bag_weight:_b("23 kg / 50 lbs","Standard economy weight"),
    car_seat:_b("Per carrier policy","Typically free; verify with operating carrier"),
    stroller:_b("Free","Most SA carriers allow 1 stroller free",true),
    ski_bag:_b("Counts as free bag","Uses your 1 free bag allowance"),
    golf_bag:_b("Counts as free bag","Uses your 1 free bag allowance"),
    sport_equip:_b("Fees apply","Alliance status does not waive sports equipment fees"),
    overweight_fee:_b("Not waived","Standard oversize/overweight fees apply"),
    checkin:_b("Priority counter","Priority check-in at all SA partner airports",true),
    security:_b("Where available","Priority security where partner offers the lane"),
    boarding:_b("Priority boarding","Board before general passengers",true),
    preboard:_b("Yes","Priority boarding ahead of general zones",true),
    seat_sel:_b("Partner policy","Varies by operating carrier"),
    exit_row:_b("No guarantee","Exit row at partner's discretion"),
    lounge:_b("No","Lounge access not included for SA Silver"),
    lounge_guest:_b("No","N/A"),
    priority_bags:_b("No","Priority baggage not included for SA Silver"),
    upgrade:_b("No","Comp. upgrades not included"),
    miles_bonus:_b("Per partner chart","Per partner's published elite earning rates"),
    fee_waiver:_b("No","Fee waivers not part of SA Silver reciprocal benefits"),
  },
  sa_gold: {
    free_bags:_b("1 free bag","1 checked bag at business-class weight limit",true),
    bag_weight:_b("Up to 32 kg / 70 lbs","Business class weight allowance",true),
    car_seat:_b("Per carrier policy","Typically free; verify with operating carrier"),
    stroller:_b("Free","Most SA carriers allow stroller free",true),
    ski_bag:_b("Varies by carrier","May count as your free bag; confirm with carrier"),
    golf_bag:_b("Varies by carrier","May count as your free bag; confirm with carrier"),
    sport_equip:_b("Fees usually apply","Not universally waived by alliance status"),
    overweight_fee:_b("Waived ≤70 lbs","Overweight waived within business-class weight",true),
    checkin:_b("Business class counter","Business class check-in at all SA partners",true),
    security:_b("Priority lane","Priority security at most SA partner airports",true),
    boarding:_b("Priority – first group","Typically first boarding group",true),
    preboard:_b("Yes","Pre-boards ahead of general boarding",true),
    seat_sel:_b("Many partners offer","Premium seat selection at many SA Gold partners"),
    exit_row:_b("Varies by partner","Exit row at partner's discretion"),
    lounge:_b("Business class lounge","Business class lounge access at partner airports",true),
    lounge_guest:_b("No","Guest not typically included for visiting SA Gold"),
    priority_bags:_b("Yes","Priority baggage delivery at most SA partners",true),
    upgrade:_b("No","Complimentary upgrades not included for visiting SA Gold"),
    miles_bonus:_b("Per partner chart","Per partner's published SA Gold earning rates"),
    fee_waiver:_b("No","Fee waivers not part of SA Gold reciprocal benefits"),
  },
  ow_ruby: {
    free_bags:_b("1 free bag","1 checked bag free; standard economy weight limit",true),
    bag_weight:_b("23 kg / 50 lbs","Standard economy weight"),
    car_seat:_b("Per carrier policy","Most oneworld carriers allow car seat free"),
    stroller:_b("Free","Stroller/pram free at all oneworld carriers",true),
    ski_bag:_b("Counts as free bag","Uses your 1 free bag allowance"),
    golf_bag:_b("Counts as free bag","Uses your 1 free bag allowance"),
    sport_equip:_b("Fees apply","Not waived as Ruby"),
    overweight_fee:_b("Not waived","Standard fees apply"),
    checkin:_b("Priority counter","Priority check-in at oneworld partner airports",true),
    security:_b("Where available","Priority security where partner provides lane"),
    boarding:_b("Priority boarding","Board before general passengers",true),
    preboard:_b("Yes","Priority boarding ahead of general boarding",true),
    seat_sel:_b("Partner policy","Varies by partner airline"),
    exit_row:_b("No guarantee","At partner's discretion"),
    lounge:_b("No","No lounge access as Ruby visiting elite"),
    lounge_guest:_b("No","N/A"),
    priority_bags:_b("No","Priority bags not included for Ruby"),
    upgrade:_b("No","Not included"),
    miles_bonus:_b("Per partner chart","Per partner's published Ruby earning rates"),
    fee_waiver:_b("No","Not included"),
  },
  ow_sapphire: {
    free_bags:_b("2 free bags","Business class baggage allowance: 2 bags at 32 kg each",true),
    bag_weight:_b("32 kg / 70 lbs","Business class weight per bag",true),
    car_seat:_b("Per carrier policy","Most oneworld carriers allow car seat free"),
    stroller:_b("Free","Stroller free at all oneworld carriers",true),
    ski_bag:_b("Varies by partner","May count as 1 of your 2 free bags; confirm with carrier"),
    golf_bag:_b("Varies by partner","May count as 1 of your 2 free bags; confirm with carrier"),
    sport_equip:_b("Varies by carrier","Some Sapphire carriers waive standard sports fees"),
    overweight_fee:_b("Waived ≤70 lbs","Overweight waived within business-class weight",true),
    checkin:_b("Business class counter","Business class check-in at all OW partners",true),
    security:_b("Priority lane","Priority security at most oneworld airports",true),
    boarding:_b("Early priority group","Early priority boarding group",true),
    preboard:_b("Yes","Pre-boards ahead of general boarding",true),
    seat_sel:_b("Many partners","Preferred seats at many OW partners at no charge"),
    exit_row:_b("Many partners","Exit row / premium economy at some partners"),
    lounge:_b("Business lounge + 1 guest","Business class lounge access + 1 guest",true),
    lounge_guest:_b("1 guest","1 accompanying guest admitted to business lounge",true),
    priority_bags:_b("Yes","Priority baggage delivery at most OW partners",true),
    upgrade:_b("No","Not included for visiting Sapphire"),
    miles_bonus:_b("Per partner chart","Per partner's published Sapphire earning rates"),
    fee_waiver:_b("No","Not typically included for visiting Sapphire"),
  },
  ow_emerald: {
    free_bags:_b("3 free bags","First/Business class allowance: 3 bags at 32 kg each",true),
    bag_weight:_b("32 kg / 70 lbs","First/Business class weight per bag",true),
    car_seat:_b("Free – uncounted","Car seat free, does not count against allowance",true),
    stroller:_b("Free","Stroller free, does not count against allowance",true),
    ski_bag:_b("Counts as 1 bag","Uses 1 of your 3 free bags (within weight limit)"),
    golf_bag:_b("Counts as 1 bag","Uses 1 of your 3 free bags (within weight limit)"),
    sport_equip:_b("Often waived","Standard sports fees frequently waived at Emerald level",true),
    overweight_fee:_b("Waived ≤70 lbs","Overweight waived within First/Business weight",true),
    checkin:_b("First class counter","First class check-in counter at all OW partners",true),
    security:_b("Priority lane","Priority security at all OW partner airports",true),
    boarding:_b("First to board","Boards immediately after special needs passengers",true),
    preboard:_b("Yes – First class","Boards with First Class cabin passengers",true),
    seat_sel:_b("Yes","Premium economy / preferred seats free; F/J on upgrade",true),
    exit_row:_b("Yes","Complimentary preferred & exit row seats",true),
    lounge:_b("First class lounges + 1 guest","Access to First & business lounges + 1 guest",true),
    lounge_guest:_b("1 guest","1 accompanying guest to First class lounge",true),
    priority_bags:_b("Yes – first off","Priority baggage at all OW partners",true),
    upgrade:_b("Varies by partner","Some OW partners offer comp. upgrades to Emerald elites"),
    miles_bonus:_b("Per partner chart","Top-tier earning rates at all OW partners"),
    fee_waiver:_b("Many partners","Many OW partners waive standard fees for Emerald",true),
  },
  st_elite: {
    free_bags:_b("1 free bag","1 checked bag free; standard economy weight limit",true),
    bag_weight:_b("23 kg / 50 lbs","Standard economy weight"),
    car_seat:_b("Per carrier policy","Typically free at most SkyTeam carriers"),
    stroller:_b("Free","Stroller free at most SkyTeam carriers",true),
    ski_bag:_b("Counts as free bag","Uses your 1 free bag allowance"),
    golf_bag:_b("Counts as free bag","Uses your 1 free bag allowance"),
    sport_equip:_b("Fees apply","Sports equipment fees not waived"),
    overweight_fee:_b("Not waived","Standard oversize fees apply"),
    checkin:_b("Priority counter","Priority check-in at SkyTeam partner airports",true),
    security:_b("Where available","Where partner airline provides priority lane"),
    boarding:_b("Priority boarding","Board before general passengers",true),
    preboard:_b("Yes","Priority boarding",true),
    seat_sel:_b("Partner policy","Varies by partner"),
    exit_row:_b("No guarantee","At partner's discretion"),
    lounge:_b("No","No lounge access as SkyTeam Elite"),
    lounge_guest:_b("No","N/A"),
    priority_bags:_b("No","Not included for SkyTeam Elite"),
    upgrade:_b("No","Not included"),
    miles_bonus:_b("Per partner chart","Per partner's published elite earning chart"),
    fee_waiver:_b("No","Not included"),
  },
  st_elite_plus: {
    free_bags:_b("2 free bags","Business class allowance: 2 bags at 32 kg each",true),
    bag_weight:_b("32 kg / 70 lbs","Business class weight per bag",true),
    car_seat:_b("Per carrier policy","Typically free; verify with carrier"),
    stroller:_b("Free","Stroller free at all SkyTeam carriers",true),
    ski_bag:_b("Varies by carrier","May count as 1 of your 2 free bags; confirm with carrier"),
    golf_bag:_b("Varies by carrier","May count as 1 of your 2 free bags; confirm with carrier"),
    sport_equip:_b("Varies by carrier","Some Elite Plus carriers waive sports fees"),
    overweight_fee:_b("Waived ≤70 lbs","Overweight waived within business-class weight",true),
    checkin:_b("Business class counter","Business class check-in at all ST partners",true),
    security:_b("Priority lane","Priority security at most SkyTeam airports",true),
    boarding:_b("Early priority group","Early priority boarding group",true),
    preboard:_b("Yes","Pre-boards ahead of general boarding",true),
    seat_sel:_b("Many partners","Preferred/extra legroom seats at many ST partners"),
    exit_row:_b("Many partners","Exit row at some SkyTeam partners"),
    lounge:_b("Business lounge + 1 guest","Business class lounge + 1 guest at ST partners",true),
    lounge_guest:_b("1 guest","1 accompanying guest to business lounge",true),
    priority_bags:_b("Yes","Priority baggage at SkyTeam partners",true),
    upgrade:_b("No","Not universally included"),
    miles_bonus:_b("Per partner chart","Per partner's published Elite Plus earning rates"),
    fee_waiver:_b("Some partners","Fee waivers at select SkyTeam partners"),
  },
};

export const SAMPLE_USER = {
  name: "Nicholas Li",
  email: "alex@example.com",
  avatar: "NL",
  tier: "premium",
  linkedAccounts: {
    aa: { memberId: "****4829", currentPoints: 68500, tierCredits: 68500 },
    dl: { memberId: "****7712", currentPoints: 32000, tierCredits: 32000 },
    ua: { memberId: "****2201", currentPoints: 18, tierCredits: 4200 },
    marriott: { memberId: "****5590", currentNights: 38, bonvoyPoints: 142000 },
    hilton: { memberId: "****3301", currentNights: 22, hhPoints: 98000 },
    ihg: { memberId: "****9102", currentNights: 8, ihgPoints: 41000 },
    hertz: { memberId: "****6610", currentRentals: 6 },
    national: { memberId: "****4455", currentRentals: 3 },
    amex_plat: { last4: "1234", pointsBalance: 145000 },
    chase_sapphire: { last4: "5678", pointsBalance: 88000 },
  },
  upcomingTrips: [
    { id: 1, type: "flight", program: "aa", route: "JFK → LAX", date: "2026-03-15", class: "premium", estimatedPoints: 4200, status: "confirmed", tripName: "LA Business Trip" },
    { id: 2, type: "hotel", program: "marriott", property: "JW Marriott LA Live", date: "2026-03-15", nights: 3, estimatedNights: 3, status: "confirmed", tripName: "LA Business Trip" },
    { id: 3, type: "flight", program: "dl", route: "LAX → ATL", date: "2026-03-18", class: "domestic", estimatedPoints: 2800, status: "confirmed", tripName: "Atlanta Connecting" },
    { id: 4, type: "flight", program: "aa", route: "DFW → LHR", date: "2026-04-10", class: "international", estimatedPoints: 9200, status: "planned", tripName: "London Spring Getaway" },
    { id: 5, type: "hotel", program: "hilton", property: "Waldorf Astoria London", date: "2026-04-10", nights: 5, estimatedNights: 5, status: "planned", tripName: "London Spring Getaway" },
    { id: 6, type: "rental", program: "hertz", location: "London Heathrow", date: "2026-04-10", days: 3, estimatedRentals: 1, status: "planned", tripName: "London Spring Getaway" },
    { id: 7, type: "flight", program: "ua", route: "SFO → NRT", date: "2026-06-20", class: "premium", estimatedPoints: 8800, status: "planned", tripName: "Tokyo Anniversary" },
    { id: 8, type: "hotel", program: "marriott", property: "Ritz-Carlton Tokyo", date: "2026-06-20", nights: 7, estimatedNights: 7, status: "planned", tripName: "Tokyo Anniversary" },
    { id: 9, type: "flight", program: "dl", route: "JFK → CDG", date: "2026-08-05", class: "international", estimatedPoints: 7500, status: "wishlist", tripName: "Paris Summer Dream" },
    { id: 10, type: "hotel", program: "ihg", property: "InterContinental Paris", date: "2026-08-05", nights: 4, estimatedNights: 4, status: "wishlist", tripName: "Paris Summer Dream" },
  ],
};

export const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

export const CREDIT_CARD_OFFERS = [
  { name: "Amex Platinum", bonus: "150,000 pts", spend: "$6k/6mo", fee: "$695/yr", color: "#B4B4B4", tags: ["Best for Lounges", "Hotel Status"] },
  { name: "Chase Sapphire Reserve", bonus: "60,000 pts", spend: "$4k/3mo", fee: "$550/yr", color: "#004977", tags: ["Best for Dining", "Travel Credit"] },
  { name: "Capital One Venture X", bonus: "75,000 mi", spend: "$4k/3mo", fee: "$395/yr", color: "#D03027", tags: ["Best Value", "Transfer Partners"] },
  { name: "Citi AAdvantage Exec", bonus: "70,000 mi", spend: "$7k/4mo", fee: "$595/yr", color: "#003B70", tags: ["AA Loyalty", "Admirals Club"] },
  { name: "Delta Reserve Amex", bonus: "90,000 mi", spend: "$6k/6mo", fee: "$650/yr", color: "#003366", tags: ["Delta Sky Club", "Companion Cert"] },
];

// ============================================================
// INSIGHTS DATA
// ============================================================
export const EXPIRATION_RULES = {
  aa:               { months: 18, note: "Any earning or redemption activity resets the clock", neverExpire: false },
  dl:               { months: 0,  note: "SkyMiles never expire", neverExpire: true },
  ua:               { months: 18, note: "Account activity (earning or redeeming) resets clock", neverExpire: false },
  sw:               { months: 24, note: "Any Rapid Rewards activity resets the clock", neverExpire: false },
  b6:               { months: 12, note: "Any TrueBlue earning or redemption activity", neverExpire: false },
  atmos:            { months: 24, note: "Any earning or redemption activity", neverExpire: false },
  flying_blue:      { months: 24, note: "Any earning or redemption activity", neverExpire: false },
  ba_avios:         { months: 36, note: "Any Avios activity in the account within 36 months", neverExpire: false },
  aeroplan:         { months: 12, note: "Any earning or redemption activity", neverExpire: false },
  singapore_kf:     { months: 36, note: "Miles expire 3 years from date earned", neverExpire: false },
  emirates_skywards:{ months: 36, note: "Miles expire after 3 years of inactivity", neverExpire: false },
  marriott:         { months: 24, note: "Any qualifying stay or points-earning activity", neverExpire: false },
  hilton:           { months: 24, note: "Any qualifying earning or redemption activity", neverExpire: false },
  ihg:              { months: 12, note: "Any points-earning or redemption activity", neverExpire: false },
  hyatt:            { months: 24, note: "Any qualifying activity (stay, purchase, transfer)", neverExpire: false },
  amex_plat:        { months: 0,  note: "Points never expire while card is open", neverExpire: true },
  amex_gold:        { months: 0,  note: "Points never expire while card is open", neverExpire: true },
  chase_sapphire:   { months: 0,  note: "Points never expire while card is open", neverExpire: true },
  chase_sapphire_pref: { months: 0, note: "Points never expire while card is open", neverExpire: true },
  cap1_venturex:    { months: 0,  note: "Miles never expire while card is open", neverExpire: true },
  bilt:             { months: 0,  note: "Points never expire while card is open", neverExpire: true },
};

export const REDEMPTION_VALUES = {
  aa:             { cpp: 1.5, best: "Business/First class intl awards via partner airlines (Cathay, JAL)", avoid: "Short domestic economy (dynamic pricing)", partners: ["ba_avios","cathay_mp","aeroplan","singapore_kf"] },
  dl:             { cpp: 1.2, best: "Delta One transcontinental, select partner awards", avoid: "Last-minute domestic (heavily inflated pricing)", partners: ["flying_blue","virgin_fc","korean_air"] },
  ua:             { cpp: 1.5, best: "Star Alliance Saver awards (ANA, Singapore, Lufthansa)", avoid: "United revenue redemptions at face value", partners: ["singapore_kf","aeroplan","turkish_miles"] },
  sw:             { cpp: 1.5, best: "Business Select fares, Companion Pass activation travel", avoid: "Wanna Get Away fares under $100 (low value)", partners: [] },
  marriott:       { cpp: 0.7, best: "Peak award nights at Category 8 properties, Points+Cash", avoid: "Low-category properties (cash rates are often cheaper)", partners: ["ua","dl","aa","ba_avios"] },
  hilton:         { cpp: 0.5, best: "Aspirational luxury properties, 5th night free on 5-night stays", avoid: "Mid-range properties (cash rates similar or better)", partners: [] },
  ihg:            { cpp: 0.5, best: "Flagship InterContinental hotels, PointBreaks sales", avoid: "Budget Holiday Inn / Staybridge (poor redemption value)", partners: [] },
  hyatt:          { cpp: 1.7, best: "Category 7–8 luxury (Park Hyatt, Alila), Points+Cash deals", avoid: "Low-category standard rooms at limited-service properties", partners: ["amex_plat","chase_sapphire","bilt"] },
  amex_plat:      { cpp: 2.0, best: "Transfer to Aeroplan/Singapore for biz class, or Virgin for PE", avoid: "Statement credits (0.6¢/pt) or gift cards", partners: ["dl","ba_avios","flying_blue","aeroplan","singapore_kf","emirates_skywards","cathay_mp","virgin_fc","marriott","hilton"] },
  chase_sapphire: { cpp: 2.0, best: "Transfer to Hyatt for luxury hotels, or Aeroplan for biz class", avoid: "Cash back via Pay Yourself Back (1–1.5¢/pt max)", partners: ["ua","sw","ba_avios","flying_blue","aeroplan","singapore_kf","emirates_skywards","virgin_fc","marriott","hyatt","ihg"] },
};
